# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYlufiLYlxfR4Z31zBqc3Uprqgaxf2N9
"""

import numpy as np
import matplotlib.pyplot as plt
import random
from random import uniform
import torch
from torch.optim import lr_scheduler
from tqdm import tqdm
from tqdm.notebook import tqdm
import time
import json
import copy
import glob
from one_time_step_opt_q import ATA_tree_tensor, ATA
from heat_opt_q_tree import ATA_tree_state, get_QFT, ATA_state, get_L, heat_source,get_random_heat, get_random_heat_2
from operations_on_trees import tree_sum, tree_multiply
from time_evolution import simulation
from drawing_graphs import run_simulation_pipeline

dd = 13
dt = 0.00001
ff = 0.99
t = 1 / 100
time_order = 10
space_order = 150
iterations = 100
run_simulation_pipeline(dd, dt, ff, t, time_order, space_order, iterations)